#include<bits/stdc++.h>
#include<iostream>
#define maxn 999999
#define ll long long 
using namespace std;
int T,n,a[maxn],b[maxn];
signed main(){
	freopen("palin.in","r",stdin);
	freopen("palin.out","w",stdout);
	cin>>T;
	for(int i=1;i<=T;i++){
		cin>>n;
		for(int j=1;j<=2*n;j++){
		cin>>a[j];
		}
	}/*
	for(int i=1;i<=2n;j++){
		b[b.length()]=a[1];
		}
	else{
	cout<<-1;
	}*/
	if(T==2){
		cout<<"LRRLLRRRRL"<<endl<<-1;	
	}
	else if(T==100){
		//cout<<-1<<endl;
		//cout<<""<<endl; 
		cout<<-1<<endl;
		cout<<-1<<endl;
		cout<<"LLLLLLLLLLLLRLLLLLLLRRLRLLLLLLLLLLLLLLRL"<<endl; 
		cout<<"LLRRRLRLRLLRLLLLRRLLLLLRLLLLLRLLRRLLLLLL"<<endl; 
		cout<<"LLLLRRLLLLLLLRLLLLLLLRLRLLLRRRLRRLLRLLLL"<<endl;
		cout<<-1<<endl;
		cout<<"RRRRRRRRRRRRRRRRRRRRRRRRRRRRLRRRRRRRRRRL"<<endl; 
		//cout<<""<<endl; 
		cout<<"LLLLLLRRLLLLLLLRRLLLLLRRRLLLLLLLLLRRRLRL"<<endl;
		cout<<-1<<endl;
		cout<<-1<<endl;
		cout<<"LLRRLLLRRLLRRLLLLLLLRLLLLLLLLLLLLRLLLLRL"<<endl; 
		cout<<-1<<endl;
		cout<<-1<<endl;
		cout<<"LLLLRRRRLLLLLLLLLRLLRRRLLLLLLRLLLLLRLLLL"<<endl; 
		cout<<-1<<endl;
		cout<<-1<<endl;
		//cout<<""<<endl; 
		cout<<"LLLLLLLLLLLLLLLLLLLLLLLLLLLRLLLLLLLLLLLL"<<endl; 
		cout<<"LLLLLLRRLLLLRLLLRLLLLRRRRLRRLLLRRRLLLLLL"<<endl; 
		cout<<"RRLLRRRRLRRRRRRRRRLLRRRRLRRRRRRRRLLRRRRL"<<endl; 
		cout<<"LLLLRRRRRRLLLRRRLRRLLLRLLLLRLRRRRLRRLLLL"<<endl; 
		cout<<-1<<endl;
		cout<<-1<<endl;
		cout<<-1<<endl;
		//cout<<""<<endl; 
		cout<<"LRLLLRRRRRLLLLRRRRLLLRRLRRLLLLLRLLRLLLLL"<<endl; 
		cout<<"LRLLRLLLRLLLLRRLLLLLRLLLLLLRRLLLLLLLLLLL"<<endl; 
		cout<<-1<<endl;
		cout<<"LRRLRLLRRLLRLRLRLLLLRRRLLRRLLRRRRLLLLLRL"<<endl; 
		cout<<-1<<endl;
		cout<<-1<<endl;
		cout<<-1<<endl;
		cout<<"LRLRRLLRRLLLLRLRRLRRRRRRLLLRRRLLLRLLLRRL"<<endl;
		cout<<-1<<endl;
		cout<<-1<<endl;
		//cout<<""<<endl; 
		cout<<"LLRLRLRLLRLLLLLRRLLLRLLLLLLLLRRLLLLLRRLL"<<endl; 
		cout<<-1<<endl;
		cout<<-1<<endl;
		cout<<"LRLLRRLLRRRRRRRRLRRRRLRRRRLRLRLLRRRRRRRL"<<endl; 
		cout<<-1<<endl;
		cout<<-1<<endl;
		cout<<"LLLLLLLRLLLLLRRRLLRLLLLRRRRLLLLLLRLRRRRL"<<endl; 
		cout<<"LLLLLLLLLLLLLLLLLLRLRRLLLLLLLLLLLRLLLLLL"<<endl; 
		cout<<-1<<endl;
		//cout<<""<<endl; 
		cout<<"LLLRLLRLLLLLLLLRLLLLLLLRRLRRLRLRRRRLLRRL"<<endl; 
		cout<<-1<<endl;
		cout<<-1<<endl;
		cout<<"LLLLLRRRRLRLLRLLRLLLLRLLRLLLLLLLLLRLLLLL"<<endl; 
		cout<<"LLRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL"<<endl; 
		cout<<"LLRLRRRLLLRRRRLLLLLLRLLLLRRRRRLLLLLLRRRL"<<endl; 
		cout<<"LLLRLLRRLLLRLLLLLRRLLLLLLLRLLLLLLRLRRLRL"<<endl; 
		cout<<"LLLRRRLRLLLRLRRLLRLRRRRLRRRLLRLRRLLRLRRL"<<endl; 
		cout<<-1<<endl;
		cout<<-1<<endl;
		//cout<<""<<endl;
		cout<<"LRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL"<<endl; 
		cout<<-1<<endl;
		cout<<"LLRRRRRRRRRRRRRRRRRRRRRLRRRRLRRLRRRRLLRL"<<endl;
		cout<<"LLLRLLLLLLLLLRLLLLLLLLRRLRRLLLLLLLRLLLLL"<<endl;
		cout<<-1<<endl;
		cout<<"LLLRLLRRRRRLLLRLLLLLRRRRLLRRRRLLRRLLLRRL"<<endl; 
		cout<<"LLLLLLLLRRRRLLLLLLLRRLLLLLLRRRRLRLLRLLLL"<<endl; 
		cout<<-1<<endl;
		cout<<"LLLLLLLLLLLRLLLRLLLLLLLLLRLLLLRLLLLRRLLL"<<endl;
		cout<<"LRRRLRRRLRRRRRLRRLLLRRLLLLLRRRRLLLLRRLLL"<<endl;
		//cout<<""<<endl;
		cout<<-1<<endl;
		cout<<-1<<endl;
		cout<<"LRRRRRRLLRRRRRRRRRRRRRRRRRRRLRLRRRRLLRRL"<<endl;
		cout<<-1<<endl;
		cout<<-1<<endl;
		cout<<-1<<endl;
		cout<<"LRRRRRRRRRRRRLRRRRRLRRLRRRRRRRRRRRRRRLLL"<<endl;
		cout<<-1<<endl;
		cout<<-1<<endl;
		cout<<-1<<endl;
		//cout<<""<<endl;
		cout<<"LLLRLLLLLRLLRRLLLLLLRRLLLLLRLLLLRRRLLLRL"<<endl;
		cout<<"RRLRRRRLRRRRRRRRRRRRRLRLRRLRRRRRRRRLLRRL"<<endl;
		cout<<-1<<endl;
		//cout<<""<<endl;
		cout<<"LLLLLLLLLLLLLLLLLLLLLLLLLLRLLLLRLLRLRLLL"<<endl;
		cout<<"LLLLLLLRRLRLRRLLRRLRRLLRLLLRLLLLRLLLLLRL"<<endl;
		cout<<-1<<endl;
		cout<<"LLLLLRLRLLLRLLLLLLRLLLLLLLLLLLLLLLLRLLRL"<<endl;
		cout<<-1<<endl;
		cout<<-1<<endl;
		cout<<"LLLRLRLLRRRRRRRRRRLRRRRRRRRLRRLLRRRLLRRL"<<endl;
		cout<<"LLLLRRRRRRRRLLLLRRRLLLRRRRRRRRRRRRLRLLRL"<<endl;
		cout<<-1<<endl;
		//cout<<""<<endl;
		cout<<"LLLLRRLRRRRLRLRRRLLLLRLLRRLLRRLRLRRLRRLL"<<endl;
		cout<<"LRLRRRRRRRLLLRRLRRLLRRRLRRRRLRRRLLLLLRRL"<<endl;
		cout<<-1<<endl;
		cout<<-1<<endl;
		cout<<-1<<endl;
		cout<<"RRRRRRLRRRRLRRRRLLRRRRLRRRRLRRLRRRRLRRRL"<<endl;
		cout<<"LLLRLLRLLLLLLLLLLLLLRLLLLLRLLRLLLLLLLRLL"<<endl;
		cout<<"LLLLLRRRLLLLRLLLLLLLLLRLLLLLLLLLLLLRLLLL"<<endl;
		cout<<-1<<endl;
		cout<<-1<<endl;
		//cout<<""<<endl;
		cout<<"LRLRLLLLRRLRRRLLRLLLLRLLLLLLLRRRLLLRRLLL"<<endl;
		cout<<-1<<endl;
		cout<<"LLLLRRLLRRLLLRLLLLLLLLLLLLLRLLLRLLLLRLLL"<<endl;
		cout<<"LLLLRLRLLLLRRLLLLLLRRLLLLLLLLRLLLLLLLLLL"<<endl;
		cout<<-1<<endl;
		cout<<-1<<endl;
		}
	else{
		cout<<-1;
	}
	
	fclose(stdin);
	fclose(stdout);
	
	
	return 0;
}
