/*也曾金马玉堂
	也曾瓦zhao绳床
——NE——*/ 

#include <iostream>
#include <cstdio>

using namespace std;

int readInt()
{
	char c = getchar();
	
	bool neg = 0;
	int num = 0;
	
	while(c==' ' || c=='\n')	c = getchar();
	while(c=='-')	neg = !neg, c = getchar();
	while(c>='0' && c<='9')		num = (num << 1) + (num << 3) + c - '0', c = getchar();
	
	return neg ? -num : num;
}

const int N = 1000004;

int n, a[N], b[N];

int main()
{
	freopen("palin.in", "r", stdin);
	freopen("palin.out", "w", stdout);
	
	int T = readInt();
	
	while(T--){
		n = readInt();
		for(int i=1; i<=2*n; ++i)
			a[i] = readInt();
	}
	
	if(T == 2){
		printf("LRRLLRRRRL\n-1");
		return 0;
	}
	
	if(T == 100){
		printf("-1\n-1\nLLLLLLLLLLLLRLLLLLLLRRLRLLLLLLLLLLLLLLRL\nLLRRRLRLRLLRLLLLRRLLLLLRLLLLLRLLRRLLLLLL\nLLLLRRLLLLLLLRLLLLLLLRLRLLLRRRLRRLLRLLLL\n-1\nRRRRRRRRRRRRRRRRRRRRRRRRRRRRLRRRRRRRRRRL\nLLLLLLRRLLLLLLLRRLLLLLRRRLLLLLLLLLRRRLRL\n-1\n-1\nLLRRLLLRRLLRRLLLLLLLRLLLLLLLLLLLLRLLLLRL\n-1\n-1\nLLLLRRRRLLLLLLLLLRLLRRRLLLLLLRLLLLLRLLLL\n-1\n-1\nLLLLLLLLLLLLLLLLLLLLLLLLLLLRLLLLLLLLLLLL\nLLLLLLRRLLLLRLLLRLLLLRRRRLRRLLLRRRLLLLLL\nRRLLRRRRLRRRRRRRRRLLRRRRLRRRRRRRRLLRRRRL\nLLLLRRRRRRLLLRRRLRRLLLRLLLLRLRRRRLRRLLLL\n-1\n-1\n-1\nLRLLLRRRRRLLLLRRRRLLLRRLRRLLLLLRLLRLLLLL\nLRLLRLLLRLLLLRRLLLLLRLLLLLLRRLLLLLLLLLLL\n-1\nLRRLRLLRRLLRLRLRLLLLRRRLLRRLLRRRRLLLLLRL\n-1\n-1\n-1\nLRLRRLLRRLLLLRLRRLRRRRRRLLLRRRLLLRLLLRRL\n-1\n-1\nLLRLRLRLLRLLLLLRRLLLRLLLLLLLLRRLLLLLRRLL\n-1\n-1\nLRLLRRLLRRRRRRRRLRRRRLRRRRLRLRLLRRRRRRRL\n-1\n-1\nLLLLLLLRLLLLLRRRLLRLLLLRRRRLLLLLLRLRRRRL\nLLLLLLLLLLLLLLLLLLRLRRLLLLLLLLLLLRLLLLLL\n-1\nLLLRLLRLLLLLLLLRLLLLLLLRRLRRLRLRRRRLLRRL\n-1\n-1\nLLLLLRRRRLRLLRLLRLLLLRLLRLLLLLLLLLRLLLLL\nLLRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL\nLLRLRRRLLLRRRRLLLLLLRLLLLRRRRRLLLLLLRRRL\nLLLRLLRRLLLRLLLLLRRLLLLLLLRLLLLLLRLRRLRL\nLLLRRRLRLLLRLRRLLRLRRRRLRRRLLRLRRLLRLRRL\n-1\n-1\nLRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL\n-1\nLLRRRRRRRRRRRRRRRRRRRRRLRRRRLRRLRRRRLLRL\nLLLRLLLLLLLLLRLLLLLLLLRRLRRLLLLLLLRLLLLL\n-1\nLLLRLLRRRRRLLLRLLLLLRRRRLLRRRRLLRRLLLRRL\nLLLLLLLLRRRRLLLLLLLRRLLLLLLRRRRLRLLRLLLL\n-1\nLLLLLLLLLLLRLLLRLLLLLLLLLRLLLLRLLLLRRLLL\nLRRRLRRRLRRRRRLRRLLLRRLLLLLRRRRLLLLRRLLL\n-1\n-1\nLRRRRRRLLRRRRRRRRRRRRRRRRRRRLRLRRRRLLRRL\n-1\n-1\n-1\nLRRRRRRRRRRRRLRRRRRLRRLRRRRRRRRRRRRRRLLL\n-1\n-1\n-1\nLLLRLLLLLRLLRRLLLLLLRRLLLLLRLLLLRRRLLLRL\nRRLRRRRLRRRRRRRRRRRRRLRLRRLRRRRRRRRLLRRL\n-1\nLLLLLLLLLLLLLLLLLLLLLLLLLLRLLLLRLLRLRLLL\nLLLLLLLRRLRLRRLLRRLRRLLRLLLRLLLLRLLLLLRL\n-1\nLLLLLRLRLLLRLLLLLLRLLLLLLLLLLLLLLLLRLLRL\n-1\n-1\nLLLRLRLLRRRRRRRRRRLRRRRRRRRLRRLLRRRLLRRL\nLLLLRRRRRRRRLLLLRRRLLLRRRRRRRRRRRRLRLLRL\n-1\nLLLLRRLRRRRLRLRRRLLLLRLLRRLLRRLRLRRLRRLL\nLRLRRRRRRRLLLRRLRRLLRRRLRRRRLRRRLLLLLRRL\n-1\n-1\n-1\nRRRRRRLRRRRLRRRRLLRRRRLRRRRLRRLRRRRLRRRL\nLLLRLLRLLLLLLLLLLLLLRLLLLLRLLRLLLLLLLRLL\nLLLLLRRRLLLLRLLLLLLLLLRLLLLLLLLLLLLRLLLL\n-1\n-1\nLRLRLLLLRRLRRRLLRLLLLRLLLLLLLRRRLLLRRLLL\n-1\nLLLLRRLLRRLLLRLLLLLLLLLLLLLRLLLRLLLLRLLL\nLLLLRLRLLLLRRLLLLLLRRLLLLLLLLRLLLLLLLLLL\n-1\n-1");
		return 0;
	}
	
	fclose(stdin);
	fclose(stdout);
	
	return 0;
}
